AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample Serverless Backend App

Parameters:
  Environment:
    Type: String
    Description: Environment code of deployment (dev, prod)
    AllowedPattern: .+
    AllowedValues:
      - dev
      - prod
  Region:
    Type: String
    Description: AWS Region
    AllowedPattern: .+
    AllowedValues:
      - ap-northeast-2
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-north-1
      - sa-east-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    Default: ap-southeast-1

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs16.x
    MemorySize: 128

Resources:
  # ========== Lambda Declaration ==========  

    NodeJSHandler:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ../handlers/
        Handler: app.mainHandler
        Runtime: nodejs16.x
        Architectures:
          - x86_64
        Environment:
          Variables:
            ENVIRONMENT: !Ref Environment
            REGION: !Ref Region

        Events:
          testGet:
            Type: Api
            Properties:
              Path: /
              Method: GET

          testPost:
            Type: Api
            Properties:
              Path: /
              Method: POST